---
abstract: 'create new pastes on sprunge.us'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.110240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Pastebin-Sprunge
requires:
  Carp: 0
  Class::Data::Accessor: 0
  Encode: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  URI: 0
  overload: 0
  perl: 5.008
resources:
  bugtracker: http://github.com/doherty/WWW-Pastebin-Sprunge/issues
  repository: git://github.com/doherty/WWW-Pastebin-Sprunge.git
version: 0.003
